### ISSUE TITLE
Disable lowercase conversion

### ISSUE THREAD

**Issue by lordlothar99** [mendixlabs/TagSelector#6]
Tags are currently automatically converted to lowerCase, which leads to several issues :
* annoying for users
* need for additional process in microflows to convert data from the database (especially for creation - duplication check -, and removal)

**Comment by JansenNick** [comment]
Hi @lordlothar99,
Just published a new release in which this is solved https://github.com/mendixlabs/TagSelector/releases/tag/2.0.0
